### ISSUE TITLE
[RFC FS-1019 Discussion]  Implicitly add the Module suffix if a type is being defined with the same name as a module

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#108]
Discussion thread for https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.1/FS-1019-implicitly-add-the-module-suffix.md if needed

**Comment by vasily-kirichenko** [comment]
It's totally great, but in addition I'd like the compiler to emit a warning if the attribute is defined by hand:
```fsharp
type A() = 
    member x.P = 1

// warning: unnecessary attribute usage
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module A =
    let create() = 1
```

**Comment by Rickasaurus** [comment]
I'm on the fence about this one. It definitely would be nice for usability, but it could cause confusing breaking changes with interop code on adding a new type, worse yet the error will suddenly occur on the C# side. The most likely people to bump into this and be confused are new F# devs still leaning on C# for the front end of their program. 

Perhaps it would be better to emit an error telling you about the attribute when there is a conflict.

**Comment by smoothdeveloper** [comment]
@Rickasaurus do you think "new F# devs" would be actively designing their code as to have a type `A` and a module `A`?

If they faced a similar need, they'll reshape a bit their business code without big impact on frontend code IMHO.

I think this feature is mostly for ML seasoned devs, and those devs who want to expose API for C# will do so with the great features that make F# to work well with C# idiomatic code.

@vasily-kirichenko will adding the warning you had in mind (can you have a more descriptive text?) lead to existing F# code to have new warnings? otherwise I think it makes sense to warn about possible redundant attribute if compiler is now handling putting suffix without requiring the attribute.

**Comment by bryanedds** [comment]
@smoothdeveloper - For example, the combination of modules and types with the same name is essential for defining abstract data types in F# - https://gist.github.com/bryanedds/87788350203a6a0527d9

I believe that abstract data types should be one of the first design tools people reach for in F#. Otherwise, you tend to either fall back into the OOP pit of complexity or just end up with a hair piles of functions and over-exposed record types with invariants that are poorly enforced (a different but also unfortunate pit of complexity). Advocacy for both abstract data types and functional programming has been prevalent in academia for just as long, but for some reason, data abstraction has not yet been similarly popularized. Here's my advocacy piece from an industrial perspective - https://vimeo.com/128464151

Since modules are so, well, weak in F#, it's not as straight-forward to define abstract data types as it should be. This proposal helps a bit, and is appreciated. I think it will be very beneficial for it to move forward. That being said, I think F# should obtain first-class support for data abstraction, say, with a bit of new syntax. However, that's a lot of work to specify well, not to mention implement, so I don't know if there will be much effort in this direction until our industry - or at least the functional side of it - starts to get a better understanding of the need for functional (as opposed to object-oriented) data abstraction.

**Comment by dsyme** [comment]
> @dsyme - If you'd be willing to talk about having me put together an RFC for such a feature, please let me know. I'd probably be willing to implement it too once I get time.

**Comment by dsyme** [comment]
@vasily-kirichenko There is a corner case mentioned in the RFC where the attribute might still theoretically be needed (basically a signature that hides the type but not the module)

**Comment by kurtschelfthout** [comment]
Overall this feels to magical for me, but I'm convinced this should not happen when there are types with the same name that are generic.

I like being able to overload names by generic type arguments. See for example in FsCheck -  @enricosada referenced in the PR for this RFC (https://github.com/Microsoft/visualfsharp/pull/1319) 

FsCheck defines a `Gen<'a>` DU and a `Gen` module with the functions that manipulate the `Gen<'a>` type on it. In addition, the functions on the `Gen` module are exported to C#. Compiling that with the new F# compiler breaks _in C#_, as @Rickasaurus says. Very confusing - to save a few lines of code?

Note for example Deedle uses the same pattern: `Series<'K,'V> and `Series` module, `Frame<,>` and `Frame` module and so on.

**Comment by bryanedds** [comment]
@kurtschelfthout - For me, it's not about saving a few lines of code (the usage actually appears 25 times in my code base, tho that's still an aside). It's about enabling a user-friendly way to do data abstraction in F# without resorting to that pit of failure known as OOP.

That being said, I understand that T<'a> and T are literally different names in .NET, so I'm not sure why we would want the module suffix to be applied to module T when there is a type T<'a> - that would be a breaking change at the reflection level anyway, Is someone proposing that?

BTW - here's my talk on 'Structuring F# Programs with Abstract Data Types' - https://vimeo.com/128464151 . Data abstraction is fundamental, and F# should, IMPO, be able to do it without user-unfriendly gigantosaur attributes :)

**Comment by kurtschelfthout** [comment]
> That being said, I understand that T<'a> and T are literally different names in .NET, so I'm not sure why we would want the module suffix to be applied to module T when there is a type T<'a> - that would be a breaking change at the reflection level anyway. Is someone actually proposing that?

Yes. It's in the RFC we're discussing.

**Comment by enricosada** [comment]
I think we should favor f# code usability. 
And it's not always obvious in f# if a class/module is going to have generic argument, so just do the right thing with same names.

The c# interoperability can be fixed if it's possibile to force the previous behaviour using for example `CompiledNameAttribute` or something else (bonus point if doesnt change behavious using previous compiler), so library author see the error and can fix it, and using old compiler doesnt change api surface

**Comment by kurtschelfthout** [comment]
I've opened a PR to turn this behavior off for types with type arguments. I hope that can drive this issue further - even if not accepted. At the moment without resolution for the types-with-type-arguments issue I don't think I'll be able to use F# 4.1 compiler for FsCheck, and that bothers me.

**Comment by bryanedds** [comment]
Thanks kurt - I agree we need to push the issue regardless of the outcome.

**Comment by dsyme** [comment]
Closing as accepted for F# 4.1. Discussion may continue on this thread

**Comment by dsyme** [comment]
I'll reopen as discussion is still active on this

**Comment by dsyme** [comment]
@kurtschelfthout I agree of the need to make this change for F# 4.1, and have approved the PR, hopefuly it now gets accepted

**Comment by kurtschelfthout** [comment]
Super! With the accepted PR, I think we don't need an attribute to turn off the implicit Module in the name as that would just lead to non-compiling code.

So I am actually ok with closing this, TBH. Looks like we have an open bug https://github.com/Microsoft/visualfsharp/issues/1720 but shouldn't affect the RFC.

I will also send a PR to update the RFC to clarify the type with type arguments behavior.

**Comment by neoeinstein** [comment]
Bump @kurtschelfthout for RFC update.

**Comment by neoeinstein** [comment]
Completed and no additional comments: closing.
