### ISSUE TITLE
[RFC FS-1022 Discussion] - Override ToString for discriminated unions and records

### ISSUE THREAD

**Issue by kurtschelfthout** [fsharp/fslang-design#123]
Please discuss [RFC FS-1022](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.2/FS-1022-override-ToString-for-discriminated-unions-and-records.md) here.

**Comment by colinbull** [comment]
I have push an initial implementation for this [here](https://github.com/Microsoft/visualfsharp/pull/1589).

**Comment by mvkra** [comment]
Just wondering how hard it would be to have it generated instead? Maybe I could pitch in I know you said it may not be worth it but for some scenari but not sure what work is required. The use case I'm thinking of is logging on a server side app. ideally the more you could log without hurting performance the better. Anything with pretty printing in log files hurts, while this wouldn't totally fix it (because it's so easy for devs to log complex objects) any performance speedup would be worth it imo.

**Comment by wallymathieu** [comment]
This sounds sweet! It's more in line with what I would expect from a discriminated union. 

The potential downside I can see is if people are using the fact that tostring returns something else in order to hide the information from other parties (but that would be ugly).

**Comment by dsyme** [comment]
> The potential downside I can see is if people are using the fact that tostring returns something else in order to hide the information from other parties (but that would be ugly).

This was one of the original motivations for not overloading ToString.  But I think we were misplaced to make it the default.  You can always opt-out by implementing an information-hiding ToString in any case

**Comment by dsyme** [comment]
@neoeinstein Could you update this PR with the F# 4.2 completion information e.g. here https://github.com/Microsoft/visualfsharp/issues/2430?  thanks!!

**Comment by neoeinstein** [comment]
Completed. Now closing.

**Comment by abelbraaksma** [comment]
New location of RFC: https://github.com/fsharp/fslang-design/blob/main/FSharp-4.1b/FS-1022-override-ToString-for-discriminated-unions-and-records.md
