### ISSUE TITLE
[FSS-0001 Discussion] Support for converting a String to an Option

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/fslang-design#224]
I'm very much against https://github.com/fsharp/fslang-design/blob/master/drafts/FSS-0001-option-of-string.md because empty or whitespace strings should not be automatically converted to `None`. `Some " "` is a perfectly valid and useful value, it has nothing common with null string, which should be converted to `None` and this job is already done by `Option.ofObj`.

**Comment by rmunn** [comment]
This idea was already discussed in https://github.com/fsharp/fslang-suggestions/issues/578, and community consensus seemed to be against it. The final comment in that thread was @dsyme saying "We should probably close the RFC since I think we're some distance off an agreed design proposal." That closure has not yet happened, apparently, since the [last commit](https://github.com/fsharp/fslang-design/commit/2429b128767a3dd796292f3bf8dcce89cc4357d2) that touched this file was about two weeks earlier than @dsyme's comment. (His "we should close the RFC" comment was made on June 19, while that rename commit is from June 6).

**Comment by dsyme** [comment]
Closing per https://github.com/Microsoft/visualfsharp/pull/3135#issuecomment-344935301
