### ISSUE TITLE
[RFC FS-1060 - Nullable Reference Types] discussion

### ISSUE THREAD

**Issue by cartermp** [fsharp/fslang-design#339]
Discussion for https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1060-nullable-reference-types.md

The biggest user-facing change in the RFC is the discovery that syntax like this:

```fsharp
let len (str: string | null) = ...
```

Would be a breaking change. For example, this code is valid F# today:

```fsharp
let f2 (_ : string | null) = 1
```

And there are likely other variants of this that people could conceivably have in their code.

Thus, we are currently thinking that we will match the C# syntax:

```fsharp
let len (str: string?) = ...
```

Since it is not a source-breaking change.

**Comment by dsyme** [comment]
> Would be a breaking change. For example, this code is valid F# today:

There are other examples, e.g. compare

    type X = A of int | B | C

and

    type X = A of int | null | C

Here the reduction to perform on `|` is very non-obvious in the context of Yacc LALR parsing

**Comment by dsyme** [comment]
Other options would be

```fsharp
let len (str: Nullable<string>) = ... // for reference types compoiled as `string`, for value types Nullable<_>
let len (str: string or null) = ... 
let len (str: string || null) = ... 
```

**Comment by cartermp** [comment]
@jamessdixon You can read about this a bit here: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1060-nullable-reference-types.md#interaction-with-usenullastruevalue

In short, `None` will still map to `null`, and the only change we may consider doing is warning on `Some null` in F# code. But existing C# code that interops with F# options must still compile as it does today.

**Comment by JordanMarr** [comment]
My feedback:

I really like the "?" notation because it is concise, and I'm already used to it from C#:
`let len (str: string?) = ...`

Unimportant side question: would we would have to `open System` to use the `?` notation?

If below is also valid, then does that mean we could also substitute `T?` anywhere we would otherwise write `Nullable<T>`?  That would be a very welcome side benefit from this IMO.
`let len (str: Nullable<string>) = ...`


I really like the twist that the emitted warnings can also be tuned to emit as errors.  I would definitely want that to be the case all the time, but I can understand why it might not be the default.  Nice to have the option though.

**Comment by cartermp** [comment]
@JordanMarr 

> Would we would have to `open System` to use the `?` notation?

No, it would have to be available without opening that namespace.

> If below is also valid, then does that mean we could also substitute `T?` anywhere we would otherwise write `Nullable<T>`? 

Perhaps. We're considering how to rationalize nullable reference types with nullable value types (`Nullable<'T>`) and if syntax and analysis can equally be applied there. Note that `Nullable<string>` does not compile because the `'T` is restricted to structs.

**Comment by dsyme** [comment]
@cartermp Nullable operators are primarily present for query expressions.  Indeed Nullable in C# is primarily there for nulls in databases and LINQ

It may well raise lots of questions about nullability and database queries and database ORM mappers.  And type providers too

**Comment by cartermp** [comment]
Yeah, I'm not keen on them being used outside of that context (lacking any data, my impression is they're rarely used already). But it'd be good to keep track of nonetheless.

**Comment by dsyme** [comment]
A note on inference subtleties...

In current F#, code such as 
```fsharp
let f x = match x with null -> 1 | _ -> 2
```
places a `T: null` constraint on the inferred type. e.g. 

```
> let f x = match x with null -> 1 | _ -> 2;;
val f : x:'a -> int when 'a : null
```
If the input type is known to be nullable, then it seems reasonable to allow this:
```
let f (x: string?) = match x with null -> 1 | _ -> 2;;
val f : x:string? -> int
```
This is not so bad and is likely the behaviour we will expect, but it requires type annotations in a way that is unusual for F# code: adding the type annotation fundamentally changes what the code is about (from definition-side nullability to use-site nullability).  This is somewhat consistent with how units of measure work in in F#.

Note that in a fully fledged version of a use-site nullness feature you would expect 
```
> let f x = match x with null -> 1 | _ -> 2;;
val f : x:'a? -> int
```
However this would be a breaking change and in any case nullable annotation code can't be generic like this.

**Comment by dsyme** [comment]
A note on inference... In the prototype the following gives a warning because `obj` is used as the default for the otherwise-uninferred type of `null`
```fsharp
    let y0 = isNull null 
```
I suppose we should use `obj?` if the unconstrained type inference variable has a `'T : null` constraint as is does in this case.

**Comment by dsyme** [comment]
A note on `extern` declarations.... The default interpretation of `extern` declaration syntax in F# should perhaps be nullable.  Or we must allow the explicit declaration of nullable pointers

From CompilerLocationUtils.fs with nullable checking on:
```
    [<DllImport("Advapi32.dll", CharSet = CharSet.Unicode, BestFitMapping = false)>]
    extern uint32 RegQueryValueExW(UIntPtr _hKey, string _lpValueName, uint32 _lpReserved, uint32 & _lpType, IntPtr _lpData, int & _lpchData);
```

Here is RegQueryValueExW accepting nullable strings or not?

**Comment by dsyme** [comment]
Note on `box` and `unbox`.  There is the question about whether these have their signatures updated to this:

```fsharp
        val unbox : value:obj? -> 'T
        val box : value:'T -> obj?
        val tryUnbox : value:obj? -> 'T option
```

**Comment by dsyme** [comment]
Now compiling up FSharp.Compiler.Private using nullness checking prototype.  Just looking at the first few messages.

Here's one example of a place where we need to consider how we will update FSharp.COre:

```fsharp
    type StructuredFormatDisplayAttribute =
        inherit Attribute
        new : value:string-> StructuredFormatDisplayAttribute
        member Value: string
```
SHould `Value` here by `string` or `string?` or oblivious

**Comment by 7sharp9** [comment]
Mixing optional params and nullable params with the ? in member definitions is going to lead to a lot of confusion, as in the optional syntax:
```
            ProvidedProperty(
                name, 
                propertyType, 
                getterCode = (fun args -> Expr.FieldGet(args.[0], field)),
                ?setterCode = blah
```

**Comment by dsyme** [comment]
Note to self (and others):

The RFC currently includes the proposal to have "match on null" eliminate nullness.  

```fsharp
    match x with  // x has type string?
    | null -> ...
    | v -> ...  // in this scope v has type string
```
However this is is annoyingly hard to implement in F# and doesn't commute particularly well with other language features, e.g. tupling and nested patterns:
```fsharp
    match x, y with  // x has type string?
    | null, null -> ...
    | null, v -> ...  // in this scope v has type string
    | v, null -> ...  // in this scope v has type string
    | p -> ...  // but in this scope does p have type string * string  or string? * string?
```
This is because the type-checking of patterns happens before the analysis of the logic of pattern decomposition itself.

The "ML way" of doing this would be to use a tagged pattern something like this:

```fsharp
    match x with  // x has type string?
    | Null -> ...
    | NotNull v -> ...  // in this scope v has type string
```
You can do this today via an active pattern like this:
```fsharp
        val inline (|Null|NonNull|) : value: 'T? -> Choice<unit, 'T> 
```
however it is not compiled particularly efficiently (though that could perhaps be).  Another alternative is the non-exhaustive assertion:
```fsharp
        val inline (|AssertNotNull|) : value: 'T? -> 'T
```
with 
```fsharp
    match x with  // x has type string?
    | null -> ...
    | AssertNotNull v -> ...  // in this scope v has type string
```
but here there is no checking that `null` and `AssertNotNull` are exhaustive or even related, it requires the user to Do The Right Thing and use `null` before `AssertNotNull`. Also the capitalization looks odd.  It is however 100% efficient.

For now I am adding the above active patterns to the prototype branch to at least give us some way of systematically eliminating nullness in active patterns.

**Comment by isaacabraham** [comment]
>The RFC currently includes the proposal to have "match on null" eliminate nullness.

    match x with  // x has type string?
    | null -> ...
    | v -> ...  // in this scope v has type string

I would really rather avoid "magic" destructuring if at all possible - I can sort of see how this fits in with the current ethos in F# but some of the other stuff like inferring nullness from if / then checks etc. - that (IMHO) doesn't fit into the spirit of the F# that I know.

**Comment by cartermp** [comment]
Well, the "ethos" here is that `v` in the above example _cannot_ be `null` because we've already accounted for it. So it makes logical sense that it is non-null and should not warn when you type `v.`. Same with any conditional-based approach, such as checking `isNull x` or `x <> null`. Failing to do this would require existing code like this:

```fsharp
if str <> null then
    printfn "%d" str.Length
else
    printfn ":("
```
To be changed to bind `str` to something else just to get rid of a warning, even though `str` cannot reach the `str.Length` call unless it is non-null. Failing to account for this introduces warnings to code that is actually correct, which is likely to be interpreted as a compiler bug. I doubt many people would accept a fuzzy, "this is not in the spirit of F#" as a reason for why their completely correct code now emits a warning.

**Comment by dsyme** [comment]
@cartermp @isaacabraham I will find a balance between these positions.  We need convenient ways to eliminate nullness that fit with the ethos of F#.

It is likely we will support this:
```fsharp
match x with  // x has type string?
| null -> ...
| v -> ...  // in this scope v has type string
```
and the more explicit tagged form for nested pattern patching:
```fsharp
match x, y with  // x has type string?
| null, _ -> ...
| _, null -> ...
| NonNull v1, NonNull v2 -> ...  // in this scope v has type string
```
We won't be supporting any of the control-flow based checking.  It's completely against the the design philosophy of F#, which doesn't do that for empty list checking, or any other kind of decomposition analysis.  That's just what `match` is for.

**Comment by jamessdixon** [comment]
Why wouldn’t it match (pun intended) the option type pattern?

 

match x with  // x has type string?
| null -> ...

|  Some v -> ...  // in this scope v has type string

 

Is it because (Some or Null) compared to (Some or None) would be too confusing?  Look fugly?

**Comment by dsyme** [comment]
> Why wouldn’t it match (pun intended) the option type pattern?

null/non-null is just a separate thing to None/Some and best not to confuse the two I think

**Comment by dsyme** [comment]
Note 
```fsharp
let f (v: string?) = 
    let v = nonNull v // checks for null and raises NullReferenceException if it is null
    ...
```
is also an acceptable elimination form, likewise any function that eliminates nullness.

I don't specifically see why this feature would drive us to change the fairly basic design decision that `if...then...else` doesn't introduce new type information.  If we did change that decision, we would apply it much more broadly than this relatively corner-case part of the language (unlike C#, null checking is not that fundamental to F#)

**Comment by isaacabraham** [comment]
> We won't be supporting any of the control-flow based checking. It's completely against the the design philosophy of F#, which doesn't do that for empty list checking, or any other kind of decomposition analysis. That's just what match is for.

@dsyme you've got my whole hearted support with this decision for exactly this reason.

**Comment by dsyme** [comment]
Capturing technical parts of a discussion on slack with @cartermp 

@cartermp  says:

> I read your note about `null` analysis with `match` expressions. That has me worried... I think it makes sense to go with what you proposed for now just to see how it all "feels", but I feel ...that compiler analysis to annoy people less is going to be essential to the success of this feature

@dsyme says:
> We can definitely do the simple case of match.. with.. null... It's the other nested cases which get much harder. But tbh I think that's enough Unlike C#, F# just don't really use null much. And for F# it feels totally OK to have explicit introduction of type information, anything else would feel wrong (edited)

@cartermp says:
> I'm tentatively pessimistic about that, but this is mostly due to an absence of data on null-checking patterns and the presence of the `isNull` function as of 4.0. But I do agree that it will be far less widespread than in C#

@dsyme says:
> I think isNull is rare, people just assume non nullness. It's nothing like c#. And I suspect we use more nulls in the compiler than most F# Code, mostly for perf and data compactness. (edited)

@cartermp says:
> I think it would be a useful exercise to see how this looks with the full VisualFSharp.sln. I expect a _lot_ of warnings

@dsyme says:
> More changes may be needed as .Net libraries become non-oblivious (however that is done) Obliviousness really makes the feature very weak. I can look at Fsharp.editor tomorrow. As long as the. Net library set being imported is oblivious you really get relatively few warnings I expect. But I may be wrong

> denulling appears expensive I did about 200 warnings/day for F# code. 
> 
> I think C# code will be brutal to denull, especially anything using interfaces or delegate abstractions for cross- component or public apis. For those you get caught in a bind - use "string?" in the API for compat, or "string" because that's what you want in the long term??? If the former then you have fewer guarantees and bad code, if the latter you may accidentally remove or forget null checks that are actually needed for compat (or leave the checks lying around which is really confusing). F# code very rarely falls into that trap. There maybe some cases in fscore we care about this but very few.
> 
> Anyway, I'm now pretty confident we can ship an acceptable version of this feature that is simple enough,  and aligns well enough with whatever craziness C# invent, and is actually useful in the rare cases where it's needed, while still generally driving people to optiontuoes for full safety (no obliviousness!). There are still wrinkles to sort out but the first divide and conquer feels done.

**Comment by cartermp** [comment]
Just to underscore this point:

> but this is mostly due to an absence of data

Given that we lack hard data on null-checking patterns for F# code in the wild, I'm uncomfortable with knowingly not accounting for patterns we know to exist and be valid.

**Comment by dsyme** [comment]
> Given that we lack hard data on null-checking patterns for F# code in the wild, I'm uncomfortable with knowingly not accounting for patterns we know to exist and be valid.

There are many correct programs which will need to be adjusted. A good example is [this change](https://github.com/Microsoft/visualfsharp/pull/5790/files#diff-45e508d98f0abe27c89b92d307b30807R896).  It is unrealistic to expect a compiler to check that original code for nullness unadjusted.  And yet the code doesn't have a mistake.

Seeking to reduce the amount of adjustment that needs to be done to account for nullness is reasonable.  But it's not an absolute thing and shouldn't complexify the language design, even if the data said "there are zillions of uses of isNull".  Null-cleansing code will still require work.

**Comment by cartermp** [comment]
I'm not going to push back terribly hard on this, but this point:

> However nulls are rare in F# code.

Is an assumption that I'm quite uncomfortable with taking. We simply don't know what the shape of the bulk of F# code in the wild is.

**Comment by 7sharp9** [comment]
@cartermp / @dsyme So what are the two opposing views heres, can we see a snippet of code to show the difference in approaches, following this thread it's difficult to visualise the two view points.

**Comment by dsyme** [comment]
>  We simply don't know what the shape of the bulk of F# code in the wild is.

:) I've seen a lot of F# code over the years. For example, we used to take as many public samples of F# codebases as we could find and integrate them into testing, since 2008 (unfortunately the collection got lost during the open source process). Nulls were very statistically rare then and are rare in all other sampling I've done. Much much rarer than in C#. I'd stand by that until someone as shows otherwise. There was nothing particularly special about these codebases (indeed their earliness might have led to more use of `null`, and it's not surprising since it's really hard to use `null` in F#.  

I've only seen one codebase with pervasive use of `AllowNullLiteral`, the `OneNet` codebase from Microsoft, written largely in C#style.

But to be honest it wouldn't change much for me either way.  Making `if .. then ... else` introduce typing assumptions (and any feature that refines types or meta information without rebinding) is really not part of the F# language design, and should be considered holistically before it is added.  The implementation complexity it adds is huge, and it breaks a lot of tooling assumptions.

@7sharp9 Roughly speaking the question is whether

```fsharp
   if isNull x then ... else ...
```
should result in a typing assumption that `x` is non-null on the `else` branch.  While I'm not 100% opposed to this, there are a hundred variations on this such as 
```fsharp
   if not (isNull x) then ... 

   if not (isNull x.SomeField) then ...  // is SomeField known to be non-null?

   if not (isNull x) && not (isNull y) then ... 

   let myNullChecker x = isNull x || sWhitespace x

    if not (myNullChecker x) then ... 
```

and so on and it's not something I feel is essential.  This is partly because currently the F# type system and checker knows little or nothing of conditional control structure and indeed F# never introduces localized type assumptions for existing declarations of values, fields or anything else.

There are related discussions , e.g. whether `match x with :? int -> ... | :? string -> ...` should change the type in each branch without rebinding.  We've always taken the answer as "no".
 
So, urrently in the prototype you need to use pattern matching to elminate nullness:
```fsharp
     match x.SomeField with 
     | null -> ...
     | NonNull f -> ....
```
or an exception-raising function such as 
```fsharp
let f x = 
    let x = nullArgCheck "x" x
    ...
```

**Comment by cartermp** [comment]
I'm concerned far less with F# codebases producing `nulls` that other parts of the codebase must produce. It's the interop scenario that worries me. As the corpus of F# code that interops with .NET has only increased over time, so as all of the places where a `null` value could come in.

I'm perfectly fine with working first to make sure we're consistent for F#-to-F# scenarios, but my FUD here is that knowingly excluding variants on `null`-checking that plainly work (and are likely seen as natural to F# programmers coming from a non-ML background). We clearly cannot account for all possible cases, but limiting this to just one flavor of `match x with | null -> ...` feels rather exclusionary for a principle that most consumers of this feature will likely care little about.

**Comment by dsyme** [comment]
> ... feels rather exclusionary for a principle that most consumers of this feature will likely care little about.

"Exclusionary" or "inclusionary" are not a specific goals either, nor even well-defined :)  

It is certainly possible to define languages that don't follow principles and are full of adhoc rules. These typically require deep and special knowledge when those rules interact.  For example, knowledge such as

>  "if you refactor a null check `if isNull x and isNull y then ...` into a separate function `let f (x,y) = isNull x && isNull y`, then you need to add the DoesANullCheck attribute to the function"..... 

That's the sort of special arcane knowledge that becomes necessary...  I'm not terribly keen on features that don't interact well together.

> I don’t really accept anecdotes as arguments for this sort of thing.

It wasn't an anecdote.  It was based on about 100 F# codebases circa 2013.  I can't see that anything has changed statistically.

**Comment by dsyme** [comment]
A good example from FSharp.Editor of the kind of stuff we would be led towards accepting:
```fsharp
                if codeLens.Computed && (isNull codeLens.UiElement |> not) then ...
```
Note that `cond |> not`.  Special typechecking rules for `|> not`??  Ugggghhhhh.

**Comment by dsyme** [comment]
The changes necessary for FSharp.Editor's internal use of `null` values are here: https://github.com/Microsoft/visualfsharp/pull/5790/commits/21f4cd5096c67381cd0f7c56e802d48aef8a5727

Only about half the changes will be necessary, there are a couple of glitches related to type inference noted by //TODO NULLNESS.  The changes to the ofObj and toObj signatures also need careful thought, I think they are ok though.

There's one `isNull` check and a couple of interesting places where it wasn't 100% obvious what to do.

Note I'm not opposed to considering language constructs, but I'm not keen to operate on the principle of "make existing code that does nullchecks just work".  Looking at FSharp.Editor and FSHarp.Compiler there are just too many variations on how people null checks today.

**Comment by cartermp** [comment]
I think we need to consider the spectrum of `null` checks, which I wrote down a bit in the original text of the RFC

This:

```fsharp
if x <> null then...
```
Is far more straightforward, and likely more common, than:

```fsharp
if myCustomNullChecker x then
```

or:

```fsharp
if cond1 x && cond2 x && (* hugely complex boolean expression *) then
```

We're in agreement that users will have to adjust their code to get rid of warnings. However, knowingly excluding certain patterns on the basis that they "don't fit the ethos of F#" doesn't make sense to me. People will _not_ be happy if something that looks plainly simple (i.e., not a giant expression or custom function), like any of these:

```fsharp
if x <> null then...

if not(isNull x) then ...
```
Cause a warning on possible NRE when it's plainly obvious that an NRE would not occur.

There are clearly places where this can still happen. For example, both Kotlin and TypeScript do not understand arbitrary functions that happen to check for `null` and produce a `bool`. TypeScript also does not understand various quirks with inner functions even if they're actually safe:

```js
function broken(name: string | null): string {
  function postfix(epithet: string) {
    return name.charAt(0) + '.  the ' + epithet; // error, 'name' is possibly null
  }
  name = name || "Bob";
  return postfix("great");
}
```
So there's definitely room to work with. But I think we need to leave the door open for more `null`-checking patterns once we're confident in the core of the feature and that our interop story is solid.

**Comment by dsyme** [comment]
The door is not closed. It's just I find it really odd that this feature would drive such a change to the fundamental type checking decisions that has driven F# so far.

So we allow this:

    if x <> null then...

ok, but what of

    if x.RecordField <> null then...

or

    if x.Property <> null then...

What would stop us going the next step to add a feature to allow those things?  After all I've seen code like that in practice....  But of course it's a mess to design such a feature, and we'd be limited to the "if variable then ..." case.

One of the most fundamental features in F# and all ML dialects is that you can abstract expressions into functions.  Features like this that fail expression abstraction are very smelly  (in the words of Simon Peyton Jones) for an expression-oriented language.  TypeScript, Kotlin and other are much more statement-oriented.

Anyway I'm not totally opposed to it and will continue to consider implementation techniques. (the complexity of adding control-flow dependent typing information is a significant concern).  One technique may be to defer warning generation until control-flow-dependent information is added in PostInferenceChecks.  Another may be to carry a separate table of typing assumptions, though that would need to be propagated everywhere.

Anyway, we can discuss this as time goes on.  It's not urgent, as from the code I've converted it's not crtical to have this in place to trial and refine the feature.   And it seems rare that `if...then...` null checks are needed in F# code without some other associated logic.

**Comment by dsyme** [comment]
@cartermp Don't sweat the small design issues too much.  My aim here was divide-and-conquer this baby so we can asses the remaining elements individually, based on evidence of actual use.

I am sure we will get feedback that more succinct null elimination forms are required.

**Comment by dsyme** [comment]
@cartermp Do we have prototypes of any nullness-annotated .NET assemblies available yet?  Thanks

**Comment by dsyme** [comment]
@cartermp Do we prefer "nullness warning" or "nullability warning" or something else?

**Comment by cartermp** [comment]
@dsyme Not aware of any assemblies to play with, no. @jaredpar?

Regarding this:

> Do we prefer "nullness warning" or "nullability warning" or something else?

In what context?

**Comment by jaredpar** [comment]
No not yet. We've started the dogfooding again in the Roslyn repository though. Should have some bits out of that in a week or so.

**Comment by dsyme** [comment]
> In what context?

In error messages, e.g. "Nullness warning: Go direct to Tony Hoare, if you pass go collect £1B"

**Comment by cartermp** [comment]
I think I would prefer not having any kind of text-based classification of the warning here. I'd much prefer the message itself just contain the relevant information, such as a type mismatch. But I'll give this a feel with a prototype.

**Comment by dsyme** [comment]
> I think I would prefer not having any kind of text-based classification of the warning here. I'd much prefer the message itself just contain the relevant information, such as a type mismatch. But I'll give this a feel with a prototype.

Yes it's partly for my own purposes right now, the `/checknulls` flag applies to about 5 different warnings, all labelled with that.  I'm not sure if we're going to want to keep `/checknulls` or not at the moment it's really useful.

**Comment by boeremak** [comment]
I don't know if this is still a thing, but I just saw the talk Philip gave to NDC about this. In the talk the first question he gets is why not treat them as Option values instead of building a whole new thing. 

He answers that it will be a lot of work, especially in the interop layer, and I can see that. But I just wanted to say that it really feels like a wasted opportunity to build a new thing when we already have the Option type that, for all intents and purposes, does the same thing.

Regarding the interop code, when handled a null now it will already crash right? There is just a convention that you won't be handled a null, it is not enforced. So if you treat the nullable type as an Option it would be possible to do an Option.bind on all the parameters and  when a null is found it will just crash like it would do now. There are probably smarter ways of doing this, I am by no means a great programmer or anything.

As for backwards compat, these types are only in C# 8 right if I understand correctly? So they are only found in the most recent .Net versions, can't we do a version check somewhere.

I am not an expert by any means, just my 2 cents.

**Comment by cartermp** [comment]
@boeremak Implicitly treating any nullable reference type as an `Option<reference-type>` would mean massively breaking changes when a package adopts NRT. For example, any `string` you consume from a library today would now be an `Option<string>`. I found 14 cases of this a small (100 LoC) file in the F# tooling already; it terrifies me to think how many breaking changes that would cause for a large codebase.

Additionally, the way that the option type is compiled into .NET metadata means that it _must_ be a nullable reference type, since it uses `UseNullAsTrueValue` to emit the `None` case as `null`. C# consumers must check for `null`. If this were to change, it would be a source breaking change for any C# consumer of F# options.

**Comment by boeremak** [comment]
@cartermp I did some more reading about the C# rationale and it seems they want to transition to a place where F# already is, namely things can't be null and have to be initialised when you use/instance them. At least that is what I got from reading this: https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-csharp/

Is that correct?

Another thing, seems like quite a change especially if you keep the IL output the same. So it is purely enforced in the tooling? A `string?` in IL is just `string.` How are they doing VB.net? Or that not happening?

**Comment by cartermp** [comment]
I suggest reading the Motivation and Principles sections detailed here for a thorough rationale of the feature from an F# and .NET perspective: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1060-nullable-reference-types.md#motivation

Much of the rest of the spec is concerned more with details on what needs to be done and what they design will be, but this prelude is the framing for the feature.

**Comment by greatim** [comment]
> > Would be a breaking change. For example, this code is valid F# today:
> 
> There are other examples, e.g. compare
> 
> ```
> type X = A of string | B | C
> ```
> 
> and
> 
> ```
> type X = A of string | null | C
> ```
> 
> Here the reduction to perform on `|` is very non-obvious in the context of Yacc LALR parsing
> 
> Requiring parenthesization may be feasible but definitely fiddly to implement
> 
> ```
> type X = A of (string | null) | C
> ```

but I think it more forward-looking

**Comment by Swoorup** [comment]
Without much familiarity with the implementation details and possibly this being brought up earlier, instead of adding null-ability and all its associated syntax, Is it possible to simply treat `Nullable struct` as `ValueOption` and `Nullable` class as Option? 

i.e C# codebases featuring Nullable would automatically be seen as Option/ValueOption in F#.

**Comment by charlesroddie** [comment]
The indications are that it F# may not support NRTs at the launch of .Net 5 and that's going to be a large problem for F# as this is the [recommended timeline](https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/) for libraries to adopt NRTs.

The suggestions in the RFC are all good, but not all are necessary to support in V1 of this feature. It's important to get this feature to a minimal spec to reduce the effort to get V1 out.

### Suggestions for cuts to the RFC / moves to a "Future" section

#### "Partial alignment of nullable value types and nullable reference types."

This can be cut. Value types don't need a `T?` syntax for NRTs to be consumable in F#. The fact that generic methods over NRTs are harder to write and require a `when 'T : not struct` consraint is not a big problem and it's also a problem that C# has to deal with.

#### Omitted NonNull in pattern matching

> It is also proposed that the NonNull can be omitted for variable patterns preceded by an unqualified null pattern.

Having `x` nonnull in `match nrt with | null -> ... | x -> ...` is a convenience that can be added later. Requiring `| null -> ... | NonNull -> ...` is OK for V1.

#### Null ambivalence (obliviousness)

If necessary this can be dropped from V1 since it could add a lot of complexity in implementation. Especially droppable if there is a rollout phase in F# where the feature is opt-in: early adopters can see if obliviousness to obliviousness causes significant difficulty.

#### Unresolved question: nullability warnings on a per-file basis?

This can easily be scoped out of V1.

#### Unresolved question: UseNullAsTrueValue

This is an F# flaw and not C#/.Net's responsibiltiy to fix. Just have these type exposed as NRTs and have a migration path for Option.
