### ISSUE TITLE
[RFC FS-1081 Discussion] - Extend fixed expressions

### ISSUE THREAD

**Issue by jwosty** [fsharp/fslang-design#421]
Discussion for [RFC FS-1081](https://github.com/jwosty/fslang-design/blob/jwosty-rfc-1081/RFCs/FS-1081-extend-fixed-expressions.md)

Suggestion here: https://github.com/fsharp/fslang-suggestions/issues/761

**Comment by abelbraaksma** [comment]
The proposal explicitly states that the `fixed` statement is going to support any `byref<'t>` and any type that implements `GetPinnableReference: unit -> byref<'t>`.

The motivation seems to be that this is the same as C#. However, that's not precisely so. C# [also supports `GetPinnableReference: unit -> inref<'t>`](https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1.getpinnablereference?view=netcore-3.1) with `fixed`. For instance, here `inref<'t>` is the result-type of `ReadOnlySpan.GetPinnableReference`.

I think we should include that case. It also makes sense, because we already support `fixed` with `inref<char>` w.r.t. to `string`: `use x = fixed myStr`, where `GetPinnableReference` on string returns `inref<'t>`.

This brings up another topic: currently, in F#, you can read/write to whatever `fixed` returns, regardless whether it was an `inref` or `byref`. This issue comment (https://github.com/dotnet/runtime/issues/36989#issuecomment-636497330) suggests that the Runtime team is trying to limit the ways that read-only memory (including strings) can be modified. However, we just introduced a simple of doing that through `fixed`.

This is probably going to stay that way, unless there's a way we can let `fixed` issue a warning of some sorts when used with read-only memory. Btw, even if we flat out forbid `fixed` with read-only memory, you can still use `MemoryMarshal.CreateSpan` on a `ReadOnlySpan`.
