### ISSUE TITLE
[style-guide] Presence of shebangs in scripts

### ISSUE THREAD

**Issue by mataha** [fsharp/fslang-design#683]
Writing F# scripts is a great way of, among other things, creating project tooling to improve the development and build processes, by e.g. managing git hooks or setting up CI. Saying that, the preferable, cross-platform way of invoking a F# script is to prepend it with a shebang directive (in this case `#!/usr/bin/env -S dotnet fsi`) and make it executable in order to run it on Linux distros, macOS, WSL et al.

However, this is not mentioned at all in the de-facto [F# code formatting guidelines](https://docs.microsoft.com/en-gb/dotnet/fsharp/style-guide/formatting) and, as a consequence, formatters implementing the coding conventions of F# remove it entirely. I believe this should not be done for F# scripts (`.fsx`), while code and signature files should be fine as they currently are.

Using e.g. [Fantomas](https://github.com/fsprojects/fantomas), the following:

```fsharp
#!/usr/bin/env -S dotnet fsi --warn:5 --warnon:1182 --warnaserror+

open System
// Rest of the code...
```

Is rewritten as:

```fsharp
open System
// Rest of the code...
```

That should not be the case.

**Comment by vzarytovskii** [comment]
@nojaf fyi, might be interesting for you

**Comment by nojaf** [comment]
If the lexer/parser can capture this in the syntax tree, Fantomas can restore it.

**Comment by dsyme** [comment]
This can be captured, yes, we should treat this as an FCS/ fantomas bug

**Comment by mataha** [comment]
What's the next step then? Do I file a bug report in Fantomas, then try to fix it before v5 hits?

**Comment by nojaf** [comment]
The next step would be to raise a PR to `dotnet/fsharp` that adds the shebang as [ParsedHashDirective](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-parsedhashdirective.html) (I think).

You can open an issue in Fantomas, but you would get the same reply there.
This doesn't hinder the v5 release, we would accept a fix at any time for this.

**Comment by nojaf** [comment]
Actually, after taking another look at this, it can be solved quite easily on Fantomas' side without any compiler changes.

Looking at the [AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQDEAhAPQBXNACc%2BAIxR9YyAG5gAtAGUw0VgBdUaymQXyA7lWHJMAVl0GjrYwEZrADgBM5w8ir1hw1sIDUAHWG%2ByP6BAB6QIAC%2BQA), the shebang is parsed as a line comment. There is a bug in Fantomas that doesn't recognize this as a line comment on a single line because it does not start with `//`.

@mataha, please report an issue on Fantomas' side. You can do this using the [online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBiAhAegK4GcAnbAIwEsA7bRCgNzAFoBlMeWAFwsXbADN8yjBgHcAhoQooArELETYkgIyKAHACZZ4iqPyJChWIQDUAHUImKZiwA9IAGnBRd7dpQDm%2BVGADajiKAhAqAASdgBPAAdkNEhKdns-QMhg2lEAG1xon0SggAYHIKDIAEkKJAp2JjIAL2QCwogAFhywAF1EgF96-xbk8KivWIqEhuTUjKzfBohFbsLIAFlRawAZSkQVmjd2AAsR6cU1XJb2oK7EgPnQyKzIGngAeV41riZwtLrelPTMrynptRzIoAUTKTxen2mUDSvEgJ06c0uRWuAxiJFgsDS%2B2R41%2BaH%2BDQAzECkqVdIR2AAxSjpAByiGEaXW2MK7EImXhZ0RX36t3RmJZEDGP0mLSaJKFTAiomgiAAQoheIZEAAFcSiAC23D0gsCbI5DVOgXOQSRSRRfIxWJJwomfzFYCkEqgUpl8sVypWsGEemgOkQpVosD9rgUuog%2BsQnON3NGFsG-OtX1xoqhADZnZBXbKFUrCIgAKoRKKEP26QPB0ShijhvjpXTRiAmwJmoXxtFW3W2vHZKEAdkz2fdecQAGE0jp8KOFPh9dB2IZa7x61HDQiLjybgnOzbvnb8Q6VIPpTmPfmFogNSQdc7l2kG2uuRu47ztwLdyn7VCAJzHt255VpzSMNbxXRswGbHoXy3Dt32TEUvwOfIHSzE9EAAQV4dg9GnDUNVEWtI3AyCwFbEJX1gpM40-A8oWUP9TxHJhLzIOBgJrUD71XQojSbWMrgoqBEy7PcewJQpDgYjCsL0ZiNVYzEQIdIjHxjZ8BJgoSd3g-dewOYkUKHdCDFwMoABFECZeTsMIQj2W4oJeIg-jkUEoZ4g-BDaIORpMyWaxil4AAVHYaCYHZDHYAB1Mh4F2WtjlUvj1NczT3JEmi9IaRQnRQ-zApCmhgS48LIpiuK9mdRpEp49dTU3VEoDiDKvKyiSMzy5ZSl4MhrAeEsq0MYFrAifN8AEJSoSkGrHLqlsGtuZrPN08SgkUAdOusAAlRA4EIeByviqqZsCJySLIvo0qWnSxIdVQ-OWHa9vgWlcCvPQnmKbCNU8Z1FGIlzzTcjVcDSVwmS4SlDHwlw9CCrdltuujfxQp7DHgBZQfB9YocIGGbNrGAdnVec9AAfWEWL4oBlKgau4ZEdTAFkKhRZlmMwhRDCB5CDWWdDsqh1qpp%2BroMa9LGcQho1FmTaOa5nm%2BfYV73sIT7vt%2Bu6RfmsXbhBsGyAhxBcfxuGEZupnpcBFD5e53myFnTGDaNk2qwJzNoGJznScICmqb2bWoI08Xruo1rVsCNQDNZ-yADURTlSh4HcAXaxUE6IDOwG2zc0OrkyiOIDUXzNspUz5zIBRE7KFP-drYWkuc2mc-pjyLalwo1FymPljMjgAHFuGG0bEHGyuKFT51psD0iFrfKj8-Dh01A6mOscN9Y5WA6AAGs5W9nfuHwB4KCYTUx0xN6OIdO8H1qp9ReDy04LDlbl421n6UZTfuB9Gh4aiBZHqFAyDVnQmUC8qtNZQlvg5U6c0g6pXFsJSW3lpZHhtkyNwFAy4UArgoKo2Cqy4HzEFWApRyjsCrOPJcYFG7nTnpRFqb8oRqBRqzdCYM9DaFcLQDYCg3CQOvIQIBlBQHj2gdMWBM8Lrti0i-ReLDpiEhZtMRY68IQrE1CQeAohxywAEBQNwX8ja0K4jIxh8iF44iXlCQkstWbDz0GQLUFR0gAGlECIAiBQmg7BSj71EHgwWMC6H3zUo-JBz9rHmgLg6Qk1tWZbyCTvCE%2BBjKwFMi9Ue2EMbryNsPMaE0KCSIaCpcJyVIl02QdpV%2BSNlHRzUXKcQAF8xmQdtAQgLiaS5ILCAhQFloATk5tWMxd9ZoPx1k-eezD6lEhLo4kazjXFULSG8Eys52QRDeGED4Yy4GZwQbPXWgw842KUUSbuajPHeP8irYRTxkkUFSesUpElcgZzaEc2RbkUHtzQYUQkq81HrNYuwBYCBIRSLCRM40jhWj1FiPgSkAgvDSI6EAA).

**Comment by nojaf** [comment]
@dsyme this was implemented in Fantomas a while ago, do we still need to do anything here?

**Comment by cartermp** [comment]
This can be closed as completed.
