### ISSUE TITLE
[RFC FS-1009 Discussion] Allow mutually referential types and modules in a closed scope

### ISSUE THREAD

**Issue by dsyme** [fsharp/fslang-design#76]
This is the discussion thread for "under review" RFC [Allow mutually referential types and modules in a closed scope](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.1/FS-1009-mutually-referential-types-and-modules-single-scope.md)

**Comment by smoothdeveloper** [comment]
I'm looking forward for large amount of discussions on this one, and some amount of polarity.

It seems to me that the language should **optionally** permit **"Alternative: Allow full mutual recursion across all files in an assembly"** rather than introducing things one at a time (or arbitrarily choosing the file as the scope).

This feels the most natural to imperative language users, Haskell also supports strong type inference without relying on order of declarations within a package (although rules about defining & importing modules are stricter).

I agree that explicit order of declarations and allowing only referencing what is already seen is a strong element in designing F# code, one which ends up being appreciated.

The rules WRT opening modules/namespaces and inference might need to be defined differently for code which would use this option, it seems if F# were to evolve this way, the way it works in Haskell should be the standard to measure against.

**Comment by dsyme** [comment]
> (or arbitrarily choosing the file as the scope).

To clarify, in the proposal the file is not the scope of mutual reference: the scope is always given by the ``rec``.  In the proposal, that can be as large as a file, or as small as a single module.  

I'll add that clarification and some notes on the "whole assembly" question.

**Comment by TIHan** [comment]
In **rare** cases, I've experienced some pain with types and modules not capable of being mutually referential; it does indeed lead to creating extra types that serve no purpose other than to be the workaround and/or defining classes instead of records. However, this forces me to think about my design and what I could do better to avoid this from happening in the first place.

I love the strong encouragement that F# makes, but I know there are these rare occasions where you might need to do such things. Sure, it can make the code a bit awkward, but it's rare.  I'm 50-50 on this one. Though, I think we should definitely should not go the "whole assembly" route. :)

**Comment by mjp41** [comment]
It seems this is trying to solve two problems

1. Expressiveness: Enabling recursive definitions between types, modules and lets.
2. Clarity: Removing the need to use `and` between definitions

It seems that you could factor this into two solutions. Enable `and` between `type`, `module` and `let rec`, to give the expressive power you desire.  So you would just allow 

```
  let rec x = ...
  and type T = ..
  and module m = ...
  and let rec y = ...
```
Then you can add a use of a keyword to remove the need for `and`.  I think something like

```
  rec 
     let x = ...
     type T = ...
     module m = ...
     let y = ...
```
Then you don't require the whole namespace or file to be mutually recursive, you can restrict it to where it is necessary.

**Comment by dsyme** [comment]
@mjp41 Yes, the original draft had

```fsharp
#beginrec

<declarations>

#endrec
```

Technically speaking the implementation is set up to do things either way (or both).

**Comment by matthid** [comment]
I really like what @mjp41 has done here. I would prefer that syntax as (especially) the namespace seems a bit too wide considering that there are some huge F# files out there :). 

Of course we can limit the scope by adding additional namespace statements:
```fsharp
namespace Test123

type R = { Other : string }

namespace Test456

type D = More

namespace My.Test

open Test123
open Test456
// ...

type T (r : R) = class end
type A (d : D) = class end 


namespace rec My.Test

open Test123
open Test456
// ...
type MyData (t : R) = class end
type More (a : D) = class end 

namespace My.Test

open Test123
open Test456
// ...


```
But then we might need to open everything we need again.

**Comment by dsyme** [comment]
@matthid @mjp41 At the logical level I feel comfortable with block-scoped ``rec``, and it fits naturally with the current TAST intermediate language used by F#, but syntactically I feel uncomfortable.

> Of course we can limit the scope by adding additional namespace statements:

Note you can also limit the scope by using module declarations, e.g.


```fsharp

namespace N

...

module rec SomeModel = 
    ...

module rec SomeOtherModel = 
    ...

```

**Comment by matthid** [comment]
@dsyme Sure, but then you'd change the code structure just for this feature, which is not what you want considering the type-module use case (which I think is often used for C# interop as well)....

I agree on the syntax, especially the `rec`-block doesn't feel right. On the other hand using `and` between lets, modules and types looks like a natural extension?

**Comment by dsyme** [comment]
@matthid 

> On the other hand using and between lets, modules and types looks like a natural extension?

I've added a section to the RFC discussing this option here: https://github.com/fsharp/FSharpLangDesign/commit/90d90039f6dce2b95a2ede8e5205bb2cbf79616e#diff-5329d5060daf2666e63368a332925b4f

**Comment by KevinRansom** [comment]
Okay ... 

I would like to know precisely how broken existing code would be if we retroactively made the namespace or module rec.

The reason I say that is, I would be worried if a developer started out writing code and her namespace or module initially didn't support it.  And then she discovered that she need mutually recursive types.
If the compiler started to complain the instant she added rec to the namespace or module or worse ... the semantics of her original code changed as a consequence of adding this ... then she would either go back to using 'and'  ... or create a whole new module or namespace just to support these few recursive types.  Neither is a particularly satisfying outcome.

As a consequence, I was wondering if adding rec would be intrusive on existing code, and I'm not sure I believe it should.

One example is what should happen if a type is discoverable both from an opened namespace and also from the local recursive namespace.  I would suggest that by definition the local namespace item should hide imported names.  So that is probably not an issue.

Are there other examples where existing code would be broken by the application of a rec to a module or namespace.

Kevin

**Comment by dsyme** [comment]
@KevinRansom A basic example is where you redefine one of the FSHarp.Core operators, e.g.

```fsharp

module rec M = 
    let f x = id x
    let id x = failwith "fail!"

```

Without the ``rec``, the ``id`` in ``id x`` resolves to ``FSharp.Core.Operators.id``.  With the ``rec``, it resolved to the function you are defining.

Whether this is worthy of a warning or not is an interesting question.  When ``rec`` is used, you could imagine re-resolving all names under an interpretation where ``rec`` is not present and checking all the resolutions are stable (and emit a warning if they are not)

**Comment by dsyme** [comment]
Closing as RFC has been accepted in F# 4.1
