### ISSUE TITLE
[RFC FS-1011 Discussion] Warn when recursive function is not tail-recursive

### ISSUE THREAD

**Issue by neoeinstein** [fsharp/fslang-design#82]
This is the discussion thread for "under review" RFC [Warn when recursive function is not tail-recursive](https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1011-warn-on-recursive-without-tail-call.md)

**Comment by wallymathieu** [comment]
I think it could be useful to get a "warning" of [level 2](https://msdn.microsoft.com/en-us/library/13b90fz7.aspx) when recursive functions are not tail-recursive. It's not such a big issue (in normal business code), but it could potentially get you into trouble.

**Comment by wallymathieu** [comment]
That is, perhaps having an information level warning about non tail recursive function in general?

**Comment by TheInnerLight** [comment]
If this going to be done via an attribute then it absolutely should be a compiler error, not just a warning.  I can't see any circumstance where it would be advantageous to tag a function with effectively a tail call suggestion.

A compiler error would be useful when working on your own projects because it allows you to impose useful constraints but it becomes, in my opinion, an absolute necessity when library code is considered.

Imagine working with a library and seeing `[<TailCall>]` attached to a function.  You could be forgiven for assuming that function would be tail recursive.  If the library author ignored the warning and published the code anyway, the attribute would suddenly become actively harmful because it now provides misinformation.

If, by contrast, `[<TailCall>]` generated a compiler error when the function it is attached to is not tail recursive, you would only ever see that attribute attached to functions where that optimisation was successfully applied.

I would also add that I think that adding 'suggestions' that aren't applied at the cost of preventing compilation seems very much at odds with the spirit of type-safe functional programming which is all about guarantees.

**Comment by wallymathieu** [comment]
Yes. That would make more sense @TheInnerLight . It would break existing code though. Could you mark an assembly in some way to get the extra type safety?

**Comment by jack-pappas** [comment]
I realized today that the solution I had in mind (which I've detailed a little before, but not well enough) is specifically geared towards warning on non-tail-recursive calls, rather than the more-general case of detecting non-tail-calls. Anyway, here's what I have in mind for the non-tail-recursive call detection:

If we can build up a call graph, or rather, a call multigraph, where edges are labeled by some information identifying a specific call site (and nodes are methods/functions), we can use something like [Johnson's algorithm](http://www.cs.tufts.edu/comp/150GA/homeworks/hw1/Johnson%2075.PDF) to identify all of the simple cycles -- each cycle will represent some chain of recursive calls (which could be as simple as a function calling itself).

Any call sites which aren't part of a cycle can immediately be dropped from consideration; they may warrant further analysis to see if they should/could be made tail calls, but for the purposes of detecting recursion they're irrelevant. Any call sites where we've detected a cycle should be tail calls -- if they're not, we'll issue a warning (since there could be unbounded recursion which ends up overflowing the stack). I think this simple analysis could be a useful start to this analyzer, as it would detect the most obviously-wrong cases that may trip up inexperienced F# developers.

The analysis could be extended and refined too, by doing some static analysis to detect cycles in the call graph where e.g., some higher-order function accepts a function-typed parameter and calls it; if we consider (for the analysis) functions which are passed into that parameter, we can be pessimistic and warn the user when there's a possibility the call site could lead to unbounded recursion (assuming the higher-order function isn't public; if it is, we have to switch to being optimistic since we can't know everything that could be passed in).

Note that the analysis I described doesn't require any additional keywords or attributes, it can be implemented for today's F# code.

**Comment by KevinRansom** [comment]
@jack-pappas 

I think in general a way of identifying non-tail calls is interesting, but at best it's a hint to the developer that we may be able to tail call since we don't have access to the information that the Jit has we won't be able to guarantee that the call will treated as tail-recursive by the Jit.

What's more, support for tailcall optimizations and the .tail opcodes are not required in a cli compatible runtime project N for example still doesn't support F# style TCO.

I am in favor of warning that for let rec foo = .... we are sure the code won't be tailcall optimized, however, a separate keyword seems really iffy given how vague the promise that TCO will happen anyway.

I don't have a large care factor whether it is directly in the compiler or as an analyzer.  However it should be noted that as an Analyzer we can build much nicer IDE experiences around it, and make enabling it and disabling it much simpler.  If it is in the compiler then it will be emitted every let rec that isn't possible to TCO and that will get old fast and likely be an automatic disable on most projects.

Warning levels is a possible enabling mechanism in the compiler, however it's not really clear that we have done a good job of being systematic about warning levels.  Developers seem to select one of two options "the default --- whatever the system gives you for warning levels if you do nothing"  or "the highest --- if they think they gain some benefit from it"

Attributes may be interesting if the IDE does a Clippy and says "I notice that you have used 
````
let rec foo = blah
````
Should it require TCO?, then the IDE can mark it correctly as you type it ... or something

Anyway my 2 cents and worth everything you paid ....

Kevin

**Comment by KevinRansom** [comment]
This is the design thread in fslang-design for

**[RFC FS-1011 Discussion] Warn when recursive function is not tail-recursive**

Okay there is a huge and interesting thread over here: https://github.com/Microsoft/visualfsharp/pull/1976#issuecomment-277384306

A little mention for everyone who participated so they get to see this design thread.

@AviAvni, @abelbraaksma, @vasily-kirichenko, @forki, @thinkbeforecoding, @vladima, @theimowski, @TeaDrivenDev, @OnurGumus, @OnurGumus, @0x53A, @isaacabraham, @matthid, @ncave, @rojepp, @jack-pappas @dsyme @cartermp  


Thanks 

Kevin

**Comment by matthid** [comment]
Just to add to the discussion. I feel like when adding this attribute no matter if we emit a warning or an error the compiler should tell me WHY it is not considered tail recursive. For example I've just seen some code [here](https://github.com/fsharp/FAKE/issues/2036#issuecomment-429624629) where apparently the code was not tail recursive and after some magic change (removing a parameter) it worked.

In other words: If I add the attribute to the linked code-fragment I expect the compiler to tell me why this would not work (might be a good test-case if this was by design) and not just fail with a generic error message (even if that would be already progress).
